### ISSUE TITLE
wowser terminates abruptly on Windows (during BLP processing)

### ISSUE THREAD

**Issue by petersandor** [timkurvers/wowser#23]
Hi, this may be related to issue reported in dependency https://github.com/timkurvers/blizzardry/issues/51

There is no error message on crash, I had to search where the app crashes: https://github.com/timkurvers/wowser/blob/master/lib/server/pipeline/index.js#L62-L72
(it doesn't crash when I send a randomly coloured PNG back)

After the crash I get -1073741819 from echo %ERRORLEVEL% (access violation)

Any help greatly apprieciated

Thanks

Peter

**Comment by timkurvers** [comment]
Did you do anything out of the ordinary to get `FreeImage` to compile on Windows? Ran into some issues there. Will have a closer look at it later this week.

**Comment by petersandor** [comment]
I did some changes in FreeImage, there was a missing include for std::min and std::max, see
https://github.com/petersandor/BLPConverter/commit/6e32084d5e1439c6a4228e7466b3d790e8258434

I can provide compiled DLLs (both 32 and 64 bit) if you need.

**Comment by petersandor** [comment]
Finally made progress! Seems like using `msvcr120` in [blizzardry/lib/c-lib.js](https://github.com/timkurvers/blizzardry/blob/master/lib/c-lib.js#L14) is enough. So this requires some platform detection to use that instead of `libc`.

Also making sure that [Visual C++ Redistributable 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784) is installed

**Comment by petersandor** [comment]
Confirmed, fixed by https://github.com/timkurvers/blizzardry/commit/ef7672f09e732c79cbb2d3df30351ef12da12411 and https://github.com/Kanma/BLPConverter/pull/5 Closing this issue.

**Comment by timkurvers** [comment]
Yay, thanks so much for looking into this! :+1:

**Comment by DDuarte** [comment]
@petersandor: did you test this on 32 or 64 bits? I'm getting the same issues on the `fseek` (the pointer returned by fopen doesn't seem to be valid) however I'm using VS 2015 with everything compiled to 64 bits.

Already tried changing the 'msvcr120' by 'msvcrt' (MS dropped versioned redistributables last year) without success.
