### ISSUE TITLE
Ignore compiled code

### ISSUE THREAD

**Issue by petersandor** [timkurvers/wowser#29]
As you already did in blizzardry dependency https://github.com/timkurvers/blizzardry/commit/34e2b886451db2a6f70cfff0a53c0e6d88c72b9f

Thanks!

**Comment by timkurvers** [comment]
Good point! Covered by 280fc71ff546166b961c0f192cb267115b91a5b5...47993daeeaeca82537dc996999f1aaf33deec4f2.

**Comment by petersandor** [comment]
I think we should ignore scripts and styles in public directory too, see https://github.com/timkurvers/wowser/pull/32

**Comment by petersandor** [comment]
Closing as this is now resolved by 0791827860e5805406453c47b848a4dada92a762...bc6daa4bbd6e44257340b3b6eec29416068066c3

**Comment by timkurvers** [comment]
:tada: :+1:
