### ISSUE TITLE
Allow configuring data directory and other client data

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/wowser#30]
Perhaps even allow configuring the data directory by argument:

```
npm run serve /wow-data
```

**Comment by petersandor** [comment]
Great idea. Also, I think there are more settings that could be customized. For example, there are further client data currently hardcoded in [lib/client/config.coffee](https://github.com/timkurvers/wowser/blob/master/src/scripts/lib/client/config.coffee#L10-L16)

So maybe a more general way to handle custom settings could be introduced? Something like, questions in CLI where the user would input settings on first run?

**Comment by timkurvers** [comment]
Ah! Very good point, had forgotten about those. Yeah, something like that would be super neat. :+1:

**Comment by timkurvers** [comment]
Documented in 3bda86d1654d434484a76550298b6ecf4067ddb7 until the configuration bit is in place.

**Comment by petersandor** [comment]
My implementation of configurable settings can be seen here https://github.com/petersandor/wowser/commits/feature/configuration (currently it handles only data directory)

Going to rewrite that to ES6. Any feedback appreciated!

**Comment by timkurvers** [comment]
Covered by #36.
