### ISSUE TITLE
Default data directory platform independence

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/wowser#37]
Make the [default data directory](https://github.com/timkurvers/wowser/blob/master/src/scripts/lib/server/utils/server-config/setup-prompts.js#L7) platform-independent using `process.platform`:

```javascript
default: 'C:/Program Files (x86)/World of Warcraft/Data'
```

If we're feeling really fancy we could even look at `process.arch` to hop into `Program Files (x86)` or regular `Program Files`.

**Comment by petersandor** [comment]
That is indeed a good idea, but `Program Files` on Windows is mainly for 64 bit applications. 
And from what I've googled, Blizzard introduced 64 bit client only in patch 4.3.2 (making this change irrelevant), see http://wowwiki.wikia.com/64-bit_client 

Just as an example, I have 64 bit OS, but the client is 32 bit so it's installed in `Program Files (x86)` regardless. #windowsstuff

**Comment by timkurvers** [comment]
I was thinking of supporting Mac's `/Applications/World of Warcraft/Data` mainly.

At present we only support 3.3.5 though, would that change anything for where the client is to be found?

**Comment by petersandor** [comment]
Yes, but only on Windows. As I mentioned, 64 bit software is located in `Program Files` and 32 bit stuff in `Program Files (x86)`. These two directories coexist.

So I think we should rather check for the OS type and based on that provide a default value (either `Program Files (x86)` or `/Applications/World of Warcraft/Data`)

**Comment by timkurvers** [comment]
Oh sorry, I always thought the folder was called `Program Files (x64)`!

Yep, sounds good! :+1:

**Comment by petersandor** [comment]
Implemented in https://github.com/timkurvers/wowser/pull/38
