### ISSUE TITLE
install error on node v0.12 on OSX

### ISSUE THREAD

**Issue by kumavis** [timkurvers/wowser#46]
this looks like a case of OSX's explosive linter
* [console output](https://gist.github.com/kumavis/c5ae1ba5b7ca2fa0e2d2)
* [npm-debug.log](https://gist.github.com/kumavis/00199b05ceff842f8cfa)

**Comment by petersandor** [comment]
I think it's the base64 install issue (websockify dependency) https://github.com/timkurvers/wowser/issues/25 currently reported at base64 official repo. 

I'm currently running websockify without base64 since node has its own implementation now

**Comment by timkurvers** [comment]
It turns out websockify had actually removed the need for pkrumins/node-base64 a very long time ago, but it was never removed. Have opened kanaka/websockify#185.

**Comment by timkurvers** [comment]
Upgraded `websockify` in 191741e8dc150261e4e05585dbf6f62ccfb8c569.
