### ISSUE TITLE
Node 5, Babel 6 and npm 3

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/wowser#63]
Investigate whether these cause any problems for Wowser.

**Comment by petersandor** [comment]
I have Node 5 & npm 3 (Win7 x64), so I tried it and everything seems to work.

I had to manually compile ffi bindings and install some module dependencies manually as well (was getting require errors all over the place).

I don't fully understand the consequences of moving from previous to this new flat module system.

Also there are a couple of Riot related JS errors, but the whole pipeline is working without any issues. How cool is that :smiley:

**Comment by timkurvers** [comment]
Excellent, thanks for checking! :+1:

Will give this a go later this week. Am planning on [swapping out Riot with React](https://github.com/timkurvers/wowser/issues/57).

**Comment by timkurvers** [comment]
Seem to run into https://github.com/node-ffi/node-ffi/issues/259 immediately on Node v5. Perhaps that doesn't apply to Windows?

Adding support for Node v4.x at the very least, seeing as it's long-term support.

**Comment by timkurvers** [comment]
Node 5.1.0 was [just released](https://github.com/nodejs/nodejs.org/commit/7244bc354731318870b8205ea15f9a65d69afa7f) and supposedly includes a fix!

**Comment by timkurvers** [comment]
Node 5.1 and npm3 confirmed working. :+1:
