### ISSUE TITLE
Map namespacing

### ISSUE THREAD

**Issue by fallenoak** [timkurvers/wowser#84]
Recent versions of JS have added a ```Map()``` type to the global namespace. Unfortunately, since the Wowser map class is also named ```Map()```, it's not possible to reference JS's ```Map()``` without using the rather kludgy workaround of ```window.Map()```

Seeing as ```WorldHandler()``` is called ```WorldHandler()```, could we change the Wowser map class to be ```WorldMap()``` ?

**Comment by timkurvers** [comment]
Yep, great idea! :+1:

**Comment by timkurvers** [comment]
Covered by 680c7ab31f575bcf6de739fd19e62335676cb6f7.

**Comment by fallenoak** [comment]
Awesome! :+1:
